### PR TITLE
fix copy paste error ppo - pvo

### PR DESCRIPTION
**Pull request by N720720**
resolves: #231

### CODE REVIEW

**Comment by N720720** [comment]
make lint
pkg_resources.ContextualVersionConflict: (pycodestyle 2.6.0 (/.pyenv/versions/3.6.13/lib/python3.6/site-packages), Requirement.parse('pycodestyle<2.8.0,>=2.7.0'), {'flake8'})

Because prospector (1.3.1) depends on pycodestyle (>=2.6.0,<2.7.0) and no versions of prospector match >1.3.1,<2.0.0, prospector (>=1.3.1,<2.0.0) requires pycodestyle (>=2.6.0,<2.7.0). So, because ta depends on both prospector (^1.3.1) and pycodestyle (<2.8.0,>=2.7.0), version solving failed.

**Comment by N720720** [comment]
I tryed to fix the dependencies with poetry but without success

Because prospector (1.3.1) depends on pyflakes (>=2.2.0,<2.3.0) and no versions of prospector match >1.3.1,<2.0.0, prospector (>=1.3.1,<2.0.0) requires pyflakes (>=2.2.0,<2.3.0). So, because ta depends on both prospector (^1.3.1) and pyflakes (<2.4.0,>=2.3.0), version solving failed.

**Review by lit26 — APPROVED** [review]
LGTM

**Comment by alisalama** [comment]
Hi, just reraising this issue. The wrapper still says ppo where it should be pvo.

`# Percentage Price Oscillator
    indicator_ppo = PercentagePriceOscillator(
        close=df[close], window_slow=26, window_fast=12, window_sign=9, fillna=fillna
    )
    df[f"{colprefix}momentum_ppo"] = indicator_ppo.ppo()
    df[f"{colprefix}momentum_ppo_signal"] = indicator_ppo.ppo_signal()
    df[f"{colprefix}momentum_ppo_hist"] = indicator_ppo.ppo_hist()

    # Percentage Volume Oscillator
    indicator_pvo = PercentageVolumeOscillator(
        volume=df[volume], window_slow=26, window_fast=12, window_sign=9, fillna=fillna
    )
    df[f"{colprefix}momentum_ppo"] = indicator_pvo.pvo()
    df[f"{colprefix}momentum_ppo_signal"] = indicator_pvo.pvo_signal()
    df[f"{colprefix}momentum_ppo_hist"] = indicator_pvo.pvo_hist()`

Thanks

**Comment by bukosabino** [comment]
Hi all, 

I have implemented the changes proposed in this PR.

Please, update the version of TA to 0.9.0 to work with them.

Thanks,  @N720720 

Best, 
Dario

**Pull request closed without merging**
