### PR TITLE
Implementation of aroon indicator

### PR DESCRIPTION
**Pull request by cjaniake**
Implementation of the AROON indicator.
Reference:
https://www.investopedia.com/terms/a/aroon.asp
https://www.investopedia.com/ask/answers/112814/what-aroon-indicator-formula-and-how-indicator-calculated.asp

The Aroon indicator is a technical indicator that is used to identify when trends are likely to change direction. In essence, the indicator measures the time it takes for the price to reach the highest and lowest points over a given timeframe as a percentage of total time. 
The Aroon Up and the Aroon Down lines fluctuate between zero and 100, with values close to 100 indicating a strong trend and values near zero indicating a weak trend. The lower the Aroon Up, the weaker the uptrend and the stronger the downtrend, and vice versa.

### CODE REVIEW

**Comment by cjaniake** [comment]
I've just realized that on version 0.22.0 pandas does not provide the option of returning a Series on rolling.apply, so I had to instantiate a new Series object on each iteration

**Comment by bukosabino** [comment]
Hi @cjaniake , 

Good job!

What pandas version do you need to work comfortably?

**Comment by bukosabino** [comment]
I am checking your work, but, the aroon indicator seems not working right.

untitled

**Comment by cjaniake** [comment]
You are right, @bukosabino! I introduced a bug on the previous commit.
Thanks for noting.
New implementation using numpy: https://github.com/bukosabino/ta/pull/17

**Pull request merged**
