### PR TITLE
Add indicators and test data

### PR DESCRIPTION
**Pull request by lit26**
Adding Scheff Trend Cycle indicator
Manually copy data from tradeview charts. Testing data round to 2 decimal places 

Adding Stoch RSI indicator, percentage volume oscillator, percentage price oscillator, ulcer index

### CODE REVIEW

**Comment by bukosabino** [comment]
Congratulations on your work @lit26 

Let me know when the pull request is ready for revision!

Best,
Dario

**Comment by lit26** [comment]
Sure, you can review the previous commit. 

Best,
Tianning

**Comment by bukosabino** [comment]
Hey @lit26 ,

Sorry for the delay. I am reviewing the PR, and I have a question:

What is the origin of `ta/tests/data/cs-stc.csv`? We will need more rows in the file to test the results correctly.

Best,
Dario

**Comment by lit26** [comment]
I copy the data from tradeview.com.

**Comment by bukosabino** [comment]
Hey @lit26 ,

Your work was included in the 0.5.26 version of the library.

Thank you so much for your collaboration!

Best,
Dario

**Pull request merged**
