### PR TITLE
something like this

### PR DESCRIPTION
**Pull request by Groni3000**
I fixed this indicator. It was completely wrong.
Important things:

1. Now it returns Series with NaN values by default unless new optional method parameter `dropnans` is not True OR you can specify `self._check_fillna(self._vpt, value=-1)` instead of `value=0` to make it bfill, but I would not recommend it. Therefore it returns `self._vpt` with property `self._vpt.shape[0] <= self.close.shape[0]`.
2. Provided new optional method parameter `smoothing_factor` like in TradingView implementation of this indicator. But it's not used by default (like in pure definition of this indicator).
3. Added some type|value checking, feel free to delete it. I added them to feel safe and didn't find a place with checkers.
4. I didnt'find a place to add important comment about shifting and fill_value with series mean, so I did it in 273 line... Not in right place but ... whatever. It should be deleted, I guess.

### CODE REVIEW

**Comment by Groni3000** [comment]
test_py37 Errors with `Imports are incorrectly sorted and/or formatted` ... That's cuz of `from typing import Union` I guess ... Dunno how to fix without just deleting it and type hint.

coverage Errors cuz of new nans behaviour I guess... Well, This new behaviour is correct one, so ... You can just delete everything, but use this CORRECT indicator
`def _run(self):
        self._vpt = (self._closes.pct_change() * self._volume).cumsum()`

That's main thing

**Comment by Groni3000** [comment]
https://app.circleci.com/pipelines/github/bukosabino/ta/382/workflows/1c05ecdd-31f3-4532-88f0-c1c8c4106817/jobs/964?invite=true#step-103-16

seems like pylint error, not my.

Well, I tried to do it in `ta style`, but again, I don't think that we can fill NaN values with mean... That seems so wrong to me...

**Comment by bukosabino** [comment]
Hey @Groni3000,

Thanks for your efforts on this indicator.

Don't worry about the linter bugs. 

Can you add some tests to the code?

**Comment by Groni3000** [comment]
@bukosabino, sorry it took so long, didn't have time at all.

Glanced into your test folder, tried to make tests in your style. Didn't even try to understand what's going on in integration folder, seems like it's supposed to be automated. In unit tests I added new class and some tests for unsmoothed and smoothed versions. Though I didn't really understood why are you doing two tests... Function indicator (1st test) creates class Indicator and runs method, 2nd test uses created class Indicator and test just runs method... Seems like duplicated test for me.

And I changed VPT as I saw it in definitions mentioned in links (added them too in docs, I tried to write briefly and informatively). 

Hope it will be helpful!

**Comment by Groni3000** [comment]
And, btw, I couldn't find anything about VPT (or PVT on TradingView) on https://stockcharts.com/ to insert it in docs.

**Comment by Groni3000** [comment]
Embarrassing for me =) Lsp doesn't work and I was coding in 2 AM — these are my excuses xDD

**Comment by bukosabino** [comment]
Hi @Groni3000,

Congratulations on your work! 

Your problem was related to linters (isort and pylint). I have solved it for you: https://github.com/bukosabino/ta/pull/330/

The volume price trend indicator is now fixed and it is included in the latest version v0.11.0.

**Comment by Groni3000** [comment]
@bukosabino, thank you very much!

**Pull request merged**
